// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtdoaifkpdfgbradsxfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0ZG9haWZrcGRmZ2JyYWRzeGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzEwMzUsImV4cCI6MjA2NDIwNzAzNX0.9ubDjsSm3pppuZ0gCOZ8onNceWsdWDVqzKGxoE2vEsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);